baseURL: ""
languageCode: en-us
title: Armando
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello Stranger"
    Content: Welcome to my blog. Here you'll find a lot of cool information about a lot of cool stuff.
  socialIcons:
    - name: "facebook"
      url: "https://facebook.com"
    - name: "linkedin"
      url: "https://facebook.com"
    - name: "instagram"
      url: "https://facebook.com"


  cover:
  linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true




#suddividere con "-" e peso 
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 30
    - identifier: news
      name: News
      url: /news/
      weight: 40
      